### ISSUE TITLE
Please provide a way to hide the icon or move the app to controlpanel

### ISSUE THREAD

**Issue by jrcii** [mipstian/catch#134] opened 2016-11-21 14:09 UTC
Make sure to do the following before submitting your issue - thanks!

- [ ] Make sure you're running the [latest release](https://github.com/mipstian/catch/releases/latest). You can find your version number at the bottom of the Help menu in Catch.
- [ ] [Check the FAQ](https://github.com/mipstian/catch/wiki/Frequently-Asked-Questions), your question might be answered there.
- [ ] [Check for an open issue](https://github.com/mipstian/catch/issues), and please comment on that issue instead of creating a duplicate.

**Comment by mipstian** [comment] 2016-11-21 14:39
Duplicate of #131

**Closed by mipstian** 2016-11-21 14:39 UTC
