### ISSUE TITLE
Catch Not Launching New ShowRSS

### ISSUE THREAD

**Issue by ZoZat** [mipstian/catch#91] opened 2016-01-06 02:54 UTC
The current version of Catch goes to http://showrss.info instead of http://new.showrss.info/timeline when launched from task bar (OS X 10.11).  Is there a fix for this?

Thanks

**Comment by lepps3275** [comment] 2016-01-06 03:11
Is your custom feed reflecting http://new.showrss.info/timeline, mine is not.  So i have a similar issue.

**Comment by ZoZat** [comment] 2016-01-06 03:18
Log into the new ShowRSS.  At the bottom of your page it will have the new link.  Paste it into preferences in Catch.  That will fix your problem.

My problem still remains.

**Comment by lepps3275** [comment] 2016-01-06 03:20
i did... but it still reflects the old feed at the bottom of my page.

**Comment by mipstian** [comment] 2016-01-06 06:05
Duplicate of #84 
@lepps3275 what is reflecting what? The history in Catch is just... history, it won't match your new feed until you've downloaded more episodes off of it.

**Closed by mipstian** 2016-01-06 06:05 UTC

**Comment by ZoZat** [comment] 2016-01-06 13:57
Please stick to the original question or create new issue.

**Comment by lepps3275** [comment] 2016-01-06 14:20
I asked a question ZoZat, is your custom http://new.showrss.info/timeline, you never answered.

I quess this is not the place for help.

**Comment by mipstian** [comment] 2016-01-06 15:16
Sure this is a place for help! Civil, friendly help :)

@ZoZat is right that separate issues should be filed separately.
@lepps3275 I'm not sure I understand your issue. If my previous message doesn't cover it, could you open a separate issue so we can discuss it properly? Thanks!

**Comment by ZoZat** [comment] 2016-01-06 15:42
Why has this been marked closed?  My issue hasn't been addressed.

**Comment by mipstian** [comment] 2016-01-06 17:03
@ZoZat it's a duplicate, see issue #84 for an explanation.

**Comment by ZoZat** [comment] 2016-01-06 17:19
I apologize.  Keep up the great work!
