### ISSUE TITLE
Support new.showrss.info

### ISSUE THREAD

**Issue by creaktif** [mipstian/catch#93] opened 2016-01-10 14:02 UTC
shows is migrating to new.showrss.info, and the new generated link does not work in catch :(

Moving forward
showRSS has existed for well over 6 years already. Phew! That's a long time to be around on the internet (where, by the way, nobody knows you're a dog).

What used to be good practices and good technologies aren't so good and modern anymore, and what used to be acceptable code is not anymore. The solution? Build showRSS from the ground up, of course.

So, there we go: there's a new showRSS! You can try it today by browsing to new.showrss.info. Users with accounts on the old showRSS can migrate their account to the new showRSS by using the "Migrate Account" area in the new website. Just enter your current showRSS username and password, and a fresh account with the same username and password will be created in the new showRSS, and most of the show selections will be copied. Before doing so, please read the instructions carefully. Contact us on Twitter if you have questions or run into issues.

Not everything is good news: for the sake of simplicity, reliability and to ensure that showRSS can last longer, some problematic features are now gone: the schedule and Transmission Push do not exist anymore in the new site. This blog has also disappeared, in favor of the Twitter feed. The show request flow has been changed in favor of a much better one that needs less manual intervention. Overlaps with wrong shows should not happen anymore, and information should be more accurate.

This current website you're reading this on right now will eventually be phased out, but there's no date planned at this moment. When this happens, the new showRSS will take the place of this service, and migration will still be possible for a while. You will not need to migrate or register again if you have already done so.

What are your thoughts? Let us know!

**Comment by mipstian** [comment] 2016-01-10 15:42
Duplicate of #84

**Closed by mipstian** 2016-01-10 15:42 UTC
