### ISSUE TITLE
Failure to download a torrent prevents other RSS to be processed

### ISSUE THREAD

**Issue by jonathannaguin** [mipstian/catch#181] opened 2021-05-03 10:51 UTC
Hello,

It seems the app stops processing torrents/RSS feed when it encounters a broken link:

Could not download https://itorrents.org/torrent/d38c5c18b7ee5050b0155c51600caed2119fba3c.torrent: Error Domain=com.giorgiocalderolla.Catch.CatchFeedHelper Code=-1 "Could not download torrent file" UserInfo={NSUnderlyingError=0x7f913841ce10 {Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={_kCFStreamErrorCodeKey=-9816, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, NSUnderlyingError=0x7f9138624200 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSErrorFailingURLStringKey=https://www.limetorrents.info/home/, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFNetworkCFStreamSSLErrorOriginalValue=-9816, _kCFStreamPropertySSLClientCertificateState=0, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., _kCFStreamError<…>

After this, the process logs the following:

default	12:49:34.387361+0200	Catch	Feed Helper error (checking feed): Error Domain=com.giorgiocalderolla.Catch.CatchFeedHelper Code=-1 "Could not download torrent file" UserInfo={NSLocalizedDescription=Could not download torrent file, NSUnderlyingError=0x6000029051d0 {Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSErrorFailingURLStringKey=https://itorrents.org/torrent/d38c5c18b7ee5050b0155c51600caed2119fba3c.torrent, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, NSErrorFailingURLKey=https://itorrents.org/torrent/d38c5c18b7ee5050b0155c51600caed2119fba3c.torrent, _kCFStreamErrorCodeKey=-9816, NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made.}}}

And marks the update as failed, no other feeds get downloaded or processed.

**Comment by mipstian** [comment] 2021-05-08 15:42
Yeah, this is by design, the check either fails or succeeds. I guess this could be improved by having a per-episode success or failure status, so failed downloads could be added to "recent episodes" anyway but marked as broken. Sounds like a lot of work for a very rare issue that basically amounts to a broken feed 🤷‍♀️

**Comment by jonathannaguin** [comment] 2021-05-13 17:39
Yeah, however it's not that easy to spot the breaking episode/feed at the moment. Would be easier to just carry on in case of a download failure?

**Comment by mipstian** [comment] 2021-05-15 18:35
True, that could be surfaced better (you can see it Console, but parsing that output is hard rn, planning to make that easy with #182). However if an episode failed and everything continued, you'll never know something wrong happened.

**Comment by mipstian** [comment] 2021-05-17 17:44
Closing in favor of #185.

**Closed by mipstian** 2021-05-17 17:44 UTC
Labels: bug
