### ISSUE TITLE
Version number and New Rss website

### ISSUE THREAD

**Issue by Kyryacos** [mipstian/catch#89] opened 2015-12-21 17:07 UTC
The "Launch ShowRSS " takes you to the old website. Although the version is shown as 1.9.3 when installed it appears as 1.9.1.

**Comment by mipstian** [comment] 2015-12-21 17:31
- First issue: Dupe of #84 
- Second issue: try reinstalling, pretty sure you're still running 1.9.1
- Also: don't put two separate issues in the same github issue please :)

**Closed by mipstian** 2015-12-21 17:31 UTC

**Comment by Kyryacos** [comment] 2015-12-21 17:43
I just did once more with a clean install. When unpacked in Desktop it shows as 1.9.3. When placed in applications is loaded as 1.9.1. I can send you a video of the process if you wish.

**Comment by mipstian** [comment] 2015-12-21 17:45
Where are you looking btw? Inside Catch's `Help` menu?

**Comment by Kyryacos** [comment] 2015-12-21 19:17
I the help menu it appears correctly as 1.9.3. In the Applications, when selected it appears as 1.9.1.

![screen shot 2015-12-21 at 21 16 36](https://cloud.githubusercontent.com/assets/16388155/11939083/31f7c842-a828-11e5-91a0-b7875c18f819.jpg)

**Comment by mipstian** [comment] 2015-12-21 20:44
Hm, I don't even know what view that is. Anyways, it's probably just some old spotlight cache or something like that. If the app says 1.9.3 in the menu, you're all set.

**Comment by studiosciences** [comment] 2015-12-21 23:13
Could you have two copies of Catch installed?

**Comment by Kyryacos** [comment] 2015-12-22 06:25
did clean install. cleared out the cache as well. same thing

**Comment by mipstian** [comment] 2015-12-22 11:39
Check System Preferences -> Users and Groups -> (your user) -> Login Items
if you have Catch in two locations, there will be two copies in there as well

**Comment by Kyryacos** [comment] 2015-12-22 12:36
yeap. had three copies there. removed them all and added manually again. version number fixed automatically afterwards.

**Comment by mipstian** [comment] 2015-12-22 12:38
Glad we got this sorted out!
