### ISSUE TITLE
No longer automatically downloads the files to the Save To location

### ISSUE THREAD

**Issue by SteveBWisbey** [mipstian/catch#199] opened 2023-02-23 11:40 UTC
Catch 2.3 (793) not working it no longer automatically downloads the files to the Save To location. I t puts in the download filename with a webloc extension on both my iMac and MacBook

Make sure to do the following before submitting your issue - thanks!

- [x] Make sure you're running the [latest release](https://github.com/mipstian/catch/releases/latest). You can find your version number at the bottom of the Help menu in Catch.
- [x] [Check the FAQ](https://github.com/mipstian/catch/wiki/Frequently-Asked-Questions), your question might be answered there.
- [x] [Check for an open issue](https://github.com/mipstian/catch/issues), and please comment on that issue instead of creating a duplicate.

**Comment by mipstian** [comment] 2023-06-20 17:03
If the feed contains magnet links (which is the default) and you choose not to "open automatically", that's the intended behavior.

What is your workflow? Do you have a good reason to require .torrent files specifically, even tho it's not recommended? Then you could switch to a feed with .torrent files instead of magnets (which would be the "mirror URLs (legacy)" option if you're using ShowRSS). If not, I'd recommend turning on "open automatically".

Please reply if these suggestions don't work for you, closing in the meanwhile.

P.S. Sorry, I didn't get notifications for this issue :/

**Closed as completed by mipstian** 2023-06-20 17:03 UTC
