### ISSUE TITLE
Organize in folders by show name not working as expected

### ISSUE THREAD

**Issue by jmseguin** [mipstian/catch#52] opened 2015-01-09 11:39 UTC
OS X Yosemite 10.10.1
When I setup catch with transmission and set Torrent Files to "Organize in folders by show name", when the feed comes in, each and every file is waiting for a location to save to. With quite a few other tools, when a torrent comes in, properties such as default folder, show name and season are passed to Transmission and the torrent starts automatically.

Not sure if this is a bug for enhancement request... let you decide.

Config: ![catch-cfg](https://cloud.githubusercontent.com/assets/10462902/5679226/d8741614-97c9-11e4-81f5-a8e8976096cc.jpg)

**Comment by mipstian** [comment] 2015-01-12 16:02
It's tricky to get the Transmission config right so that it doesn't show a window when a transfer is added from Catch. But it definitely can be done, and works for me. I don't exactly recall which thing is always off in mine, but here's (what I think is) the relevant part of my Transmission config:
![screen shot 2015-01-12 at 4 57 15 pm](https://cloud.githubusercontent.com/assets/421341/5705800/36a736bc-9a7c-11e4-9b41-a562cec628c8.png)
See if this helps.

If there's a magical way to pass information like the download location to Transmission, I'd love to know (for example, what are these "other tools" you mention?). However, Catch is built to be compatible with anything that can either open .torrent files or magnet links. For that reason all it does it to tell the system to open that file/link with the default application. I'm not aware of any ways to pass additional information through these mechanisms.

Closing for now as this isn't a bug per se, but please reopen if you think it's appropriate. Thanks!

**Closed by mipstian** 2015-01-12 16:02 UTC

**Comment by jmseguin** [comment] 2015-01-13 11:26
I was using TVShows2 but once they lost their primary search, it would
require me adding custom RSS for each show. Not horrible but I looked for
an alt. I am sure others did as well. My Transmission setup worked for for
it. Start transfers when added is selected. In the case of Catch, I come to
my computer in the morning with a folder selector window open and I must
choose where it goes. In the case of TVShows2, it automatically went into a
folder setup as <start_dir>/<tv_show_name>/<season> and by morning, I was
already seeding.

Thanks.

**Comment by deep-eddy** [comment] 2015-01-26 03:13
Same issue for me. It also worked fine with tvshows2.  I just made my settings identical to yours. Let's see if it helps.

**Comment by mipstian** [comment] 2015-01-26 05:45
Let me know! Also double-check that you can write to the output folder, iirc if you can't the window pops up regardless.

**Comment by Pazu** [comment] 2015-02-24 13:34
What mechanism does Catch use to pass the transfer over to Transmission?

**Comment by mipstian** [comment] 2015-02-24 13:38
There's no Transmission-specific code, Catch only tells OS X to open a magnet: URL.

See https://github.com/mipstian/catch/blob/master/CTCBrowser.m#L32-L39

**Comment by Pazu** [comment] 2015-03-01 06:20
The torrents only start automatically if I disable magnets on ShowRSS feed. I think #57 should be re-opened. Maybe you'd have to use Transmission's RPC to tell it specifically where to save?

**Comment by mipstian** [comment] 2015-03-02 23:50
Did you try copying my settings from the screenshot above, making sure the default location folder exists and is writable? I use magnets in my feed, and torrents start automatically.
I am against writing Transmission(or anything really)-specific code.

**Comment by deep-eddy** [comment] 2015-03-03 00:07
I've been silent on this thread since I first reported having this issue,
but I'm still seeing it as well even after copying your settings from the
screenshot.


On Mon, Mar 2, 2015 at 5:50 PM, Giorgio Calderolla <notifications@github.com
> wrote:

> Did you try copying my settings from the screenshot above, making sure the
> default location folder exists and is writable? I use magnets in my feed,
> and torrents start automatically.
> I am against writing Transmission(or anything really)-specific code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mipstian/catch/issues/52#issuecomment-76854739>.
>



-- 
Chris Garrigues
cwg@DeepEddy.Com
512-213-0609

**Comment by mipstian** [comment] 2015-03-03 00:13
Maybe you guys are running into this Transmission bug, there's a possible workaround at the end: https://trac.transmissionbt.com/ticket/5834

**Comment by Pazu** [comment] 2015-03-03 16:16
I see the magnet torrents starting after changing the default location from “Same as torrent file” to some folder.

The torrents are saved to that folder instead of to the individual show folders (though Catch does still create those folders). The data file has to be moved to the individual show folder after being added to Transmission. Is *that* the expected behavior? If so, I guess I need to write some script to move the data file after addition.

**Comment by mipstian** [comment] 2015-03-04 00:29
There you go. The folder needs to be valid, and in the case of magnet links, "same as torrent file" makes no sense. Goodbye stupid window :)

Now for the second part, that pretty much is the expected behavior, although it's a bit of an edge case. The "organize..." setting in Catch only works if you're not using magnet links. Setting it and then using magnet links results in the behavior you're seeing - folders are created, but torrents aren't downloaded there.

This behavior will be made clear when we get around to doing #16, because the option to "organize" will only be offered if magnets are not used.

If you care about automatic folder organization, you need to either
1) keep your settings as they are and do it yourself, or
2) do not use magnet links, change back to "same as torrent file"

We should probably fix the weird case where folders are created even if it doesn't make sense, but I think that can wait until #16 and then it'll magically go away.
