### ISSUE TITLE
Is it possible to point <launch showRSS> to the new website for showRSS?

### ISSUE THREAD

**Issue by Outside-Kitty** [mipstian/catch#98] opened 2016-01-20 18:30 UTC
Hello, 

I was wondering if linking Catch to the new ShowRSS was a feature or update that is in the queue? 

Thanks again for a simple, super great little app. 

Kevin

**Comment by mipstian** [comment] 2016-01-20 18:37
Duplicate of #84

**Closed by mipstian** 2016-01-20 18:37 UTC
