### ISSUE TITLE
New ShowRSS generates incorrect link

### ISSUE THREAD

**Issue by Seacidal** [mipstian/catch#105] opened 2016-02-04 06:00 UTC
I have also been experiencing a complete failure to receive torrents recently. I am using the link generated by the New ShowRSS site. 
I noticed that the generated link does not reference the New site. Once I added "new." to the link and prompted Catch to "Check Now", I received a flood of backlogged shows. 
Hope this might help others resolve their problems.

**Comment by mipstian** [comment] 2016-02-04 17:08
@adrinavarro weird, I don't have "new" in my feed and it works fine... Any ideas?
@Seacidal could you post both feed urls so we can compare them?

**Comment by showrss** [comment] 2016-02-04 17:11
No need to change the link, it is intentional and there is no bug. Otherwise you will have to change the link again when the old showRSS is shut down. 

Any way to get a log of http responses? Maybe cloudflare is not playing very nice.

**Comment by Seacidal** [comment] 2016-02-04 20:16
mipstian,
My old link was:  http://showrss.info/user/1494.rss?magnets=true&namespaces=true&name=null&quality=null&re=null
My new link is: http://new.showrss.info/user/1494.rss?magnets=true&namespaces=true&name=null&quality=null&re=null
I had already tried uninstalling/reinstalling Transmission and Catch, without success. 
I read showrss' post and maybe it's something else entirely. I'm willing to try to produce a helpful log, but not sure where to find it. Thanks.

**Comment by mipstian** [comment] 2016-02-05 02:25
The only differences I can see between the two feeds are that the new one has the `new.` prefix in the `xmlns:tv` and `<link>` values, and only one of the two had a newline at the end.

I had no trouble downloading either.

I don't think those differences can cause this problem, but I guess the feed contents should be identical, right @adrinavarro ?

**Comment by reedyfj** [comment] 2016-02-05 05:55
When posting the new ShowRSS feed link into Catch, I get the yellow ! icon next to the link field upon hitting OK.  Checking my feed produces no results and after clicking "Check Now" from the Manu Bar icon, the Last Update field doesn't update from "Never".  Uninstalled/reinstalled both like the @Seacidal.

From their blog post, though I'm sure that's only referring to their in house solution, which coincidentally only worked with a much earlier release of Transmission. 

> Transmission Push does not exist anymore in the new site.

feed://showrss.info/user/21729.rss?.magnets=true&namespaces=true&name=null&quality=null&re=null

**Comment by mipstian** [comment] 2016-02-05 05:59
@reedyfj this is a completely separate issue, but in short: you're not copying the feed properly from ShowRSS. Feeds addresses accepted by Catch begin with `http`. You also have a stray `.` in there. New ShowRSS will show you the feed in a green box, just copy-paste that.

**Comment by reedyfj** [comment] 2016-02-05 08:06
@mipstian sorry, safari converted it to feed:// but http gives the same behavior.  copied straight from the green link generation: 

> Your custom feed address: http://showrss.info/user/21729.rss?magnets=true&namespaces=true&name=null&quality=null&re=null

Removing the filters (truncating from ? onward) produces the same results as well.

**Comment by adrinavarro** [comment] 2016-02-05 08:15
Please download and the install the latest version of Catch and then try
again...

Sent from my phone
On Fri, Feb 5, 2016 at 9:06 AM, reedyfj <notifications@github.com> wrote:
@mipstian [https://github.com/mipstian] sorry, safari converted it to feed:// but http gives the same behavior. copied
straight from the green link generation:

Your custom feed address: 
http://showrss.info/user/21729.rss?magnets=truenamespaces=true&name=null&quality=null&re=null]

Removing the filters (truncating from ? onward) produces the same results as
well.

—
Reply to this email directly or view it on GitHub
[https://github.com/mipstian/catch/issues/105#issuecomment-180244088] .[https://github.com/notifications/beacon/AADKagOB6GHW1LdleD48zyPPWM3OGtpbks5phE-SgaJpZM4HTGsJ.gif]

**Comment by mipstian** [comment] 2016-02-05 23:42
@Seacidal are you still experiencing the issue when using the non-`new` version of the link? If so, could you open Console.app and see if Catch logs something when you "Check now"?

**Comment by Seacidal** [comment] 2016-02-07 02:02
Sorry for my delay. I had one episode download in the last day or so. 
In Console, I saw that Catch (when I did a "Check now") reported the following:
2/6/16 5:54:53.388 PM Catch[5526]: Forcing feed check
2/6/16 5:54:53.389 PM Catch[5526]: Scheduler status updated (polling = 1, checking = 1)
2/6/16 5:54:53.394 PM com.giorgiocalderolla.Catch.CatchFeedHelper[5556]: Checking feed
2/6/16 5:54:53.395 PM com.giorgiocalderolla.Catch.CatchFeedHelper[5556]: Downloading feed http://showrss.info/user/1494.rss?magnets=true&namespaces=true&name=clean&quality=sd&re=no
2/6/16 5:54:53.743 PM com.giorgiocalderolla.Catch.CatchFeedHelper[5556]: Feed downloaded
2/6/16 5:54:53.743 PM com.giorgiocalderolla.Catch.CatchFeedHelper[5556]: Parsing feed
2/6/16 5:54:53.744 PM com.giorgiocalderolla.Catch.CatchFeedHelper[5556]: Parsed 8 files
2/6/16 5:54:53.744 PM com.giorgiocalderolla.Catch.CatchFeedHelper[5556]: Downloading files (if needed)
2/6/16 5:54:53.744 PM com.giorgiocalderolla.Catch.CatchFeedHelper[5556]: All done
2/6/16 5:54:53.744 PM Catch[5526]: Scheduler status updated (polling = 1, checking = 0)

Looks like things might be working again. I noticed that the site http://new.showrss.info now generates links without the "new" at the beginning. Interesting? I also find that Catch still takes me to the old ShowRSS site.

**Comment by mipstian** [comment] 2016-02-07 03:24
That Catch sends you to old ShowRSS is by design.

Ok then.. Guess I'm closing :)

**Closed by mipstian** 2016-02-07 03:24 UTC
