### ISSUE TITLE
Catch is preventing sleep

### ISSUE THREAD

**Issue by gnfpt** [mipstian/catch#73] opened 2015-10-03 08:47 UTC
![catch](https://cloud.githubusercontent.com/assets/9711909/10262155/aa1b9582-69b3-11e5-9578-12591554a065.png)

Catching is preventing sleep. Is it possible to fix this?

**Comment by mipstian** [comment] 2015-10-03 09:44
Duplicate of #24

**Closed by mipstian** 2015-10-03 09:44 UTC

**Comment by gnfpt** [comment] 2015-10-03 15:32
yup, saw that a few moments ago. Sorry

**Comment by mipstian** [comment] 2015-10-03 16:38
No problem, triaging issues is part of the job :)
