### ISSUE TITLE
Supporting other RSS feeds.

### ISSUE THREAD

**Issue by Gyvastis** [mipstian/catch#150] opened 2018-04-25 08:33 UTC
Hey there, lovely people. First of all, thanks for the amazing work! I just wanted to ask a quick question. Obviously, Catch is only limited to ShowRSS. But can there be an exception made to allow other domains for the RSS feed? The app works well with TV shows, but I also found a similar service for Anime. I can mix the two RSS feeds which does basically the same as the original ShowRSS feed. But of course only the ShowRSS url is allowed. What's your take on this?

**Comment by mipstian** [comment] 2018-04-25 10:50
Duplicate of #4 
Please don’t ignore the instructions in the issue template, they’re there for a reason!

**Closed by mipstian** 2018-04-25 10:50 UTC
