### ISSUE TITLE
new ShowRSS site link update

### ISSUE THREAD

**Issue by skepticus** [mipstian/catch#104] opened 2016-02-04 00:33 UTC
The "Launch ShowRSS" menu feature takes us to the old site- any quick way to fix this?

**Comment by mipstian** [comment] 2016-02-04 00:37
Click the giant "Go to new ShowRSS" button when you get there :) This issue will solve itself when new showrss supplants the old version. Duplicate of #84

**Closed by mipstian** 2016-02-04 00:37 UTC

**Comment by skepticus** [comment] 2016-02-04 01:37
> On 02 03, 2016, at 19:37, Giorgio Calderolla <notifications@github.com> wrote:
> 
> Click the giant "Go to new ShowRSS" button when you get there :) This issue will solve itself when new showrss supplants the old version.

Ah, I do click that. Was wanting to reduce that step.

And, sorry, didn’t know I was duplicating something.

Waiting is.

- Wade
