### ISSUE TITLE
http://new.showrss.info not used

### ISSUE THREAD

**Issue by NightwatchNL** [mipstian/catch#100] opened 2016-01-29 20:08 UTC
The latest update of Catch doesn't use [http://new.showrss.info](http://new.showrss.info) but the old [https://showrss.info](https://showrss.info). Is it possible to add an option to Preferences in which you can select if you use the old or new link?

**Comment by mipstian** [comment] 2016-01-29 20:59
Duplicate of #84

**Closed by mipstian** 2016-01-29 20:59 UTC

**Comment by NightwatchNL** [comment] 2016-01-29 21:08
I do not mean that the feed is supported; I know it is. But i'd like (for the time being) the option to add the new site into Catch > Launch ShowRSS.

**Comment by mipstian** [comment] 2016-01-29 21:13
The new URL is temporary and for a beta-ish version of the backend, so it's unwise to hardcode it in an app. There's now a big button in the old website to jump to the new version in one click. This will fix itself when the new version replaces the current one.

**Comment by NightwatchNL** [comment] 2016-01-29 21:30
Too bad :-)
I would think it's easy to link the "new." part of your site to the original when it's enrolled. When – in the future – you would decide to make another update, you could seperate them again and the function becomes relevant again. Smart thinking, isn't is? ;-)

**Comment by mipstian** [comment] 2016-01-29 21:36
It's not a technical issue, I could very easily make the menu launch whatever version of showrss your feed is from. I just won't add a hard link to a beta website in the app. It's near-useless and I'd be doing is adding some code that will need to be gutted in the future, and buying myself a potential bug when said URL doesn't exist anymore :/
