### ISSUE TITLE
Catch not updating

### ISSUE THREAD

**Issue by IevaLe** [mipstian/catch#125] opened 2016-10-03 05:12 UTC
Hello! 

For several days for now my Catch isn't uploading. All the uploads ends with "Last Update (Failed):time). I have the newest version and it worked week ago, but now it's not working anymore. :( 

Make sure to do the following before submitting your issue - thanks!

- [ ] Make sure you're running the [latest release](https://github.com/mipstian/catch/releases/latest). You can find your version number at the bottom of the Help menu in Catch.
- [ ] [Check the FAQ](https://github.com/mipstian/catch/wiki/Frequently-Asked-Questions), your question might be answered there.
- [ ] [Check for an open issue](https://github.com/mipstian/catch/issues), and please comment on that issue instead of creating a duplicate.

**Comment by yashendra2797** [comment] 2016-10-03 07:43
Yup. Me too.

**Comment by yashendra2797** [comment] 2016-10-03 07:43
Check this: https://github.com/mipstian/catch/issues/124

Switch to magnet and see if it works.

**Comment by yashendra2797** [comment] 2016-10-03 07:48
Yup, switching to magnet immediately cleared my backlog. 

Here's how to do it:

1. Click on Catch icon in the menu bar.

2. Click on preferences

3. In Feed URL, change `magnets=false` to `magnets=true`

4. Ensure 'Open Automatically' is checked (otherwise you'd get a bunch of .webloc files that may be confusing if you're a noob)

**Comment by mredrup** [comment] 2016-10-03 09:37
I also have the same problem - the odd show will download but the majority don't.  Magnets are not very convenient when using Transmission as the clients due to the windows that open. This might actually be a ShowRSS issue and not catch.  the "failed" message has been there for sometime but the shows still downloaded.

**Comment by mipstian** [comment] 2016-10-03 11:20
Duplicate of #124

**Closed by mipstian** 2016-10-03 11:20 UTC
