### ISSUE TITLE
Update failed when not using magnets

### ISSUE THREAD

**Issue by Seb137** [mipstian/catch#124] opened 2016-10-01 16:13 UTC
Hello everyone,

I notice Catch doesn't work anymore with torrent file (last update failed when I check for new torrent with my feed link) but only with magnet link. I did some trial with options on showrss but still not work. Magnets are generating webloc files and this is a nightmare to manage and add in my rutorrent seedbox...

Anyone has this problem too? (please tell me I am the only one...)
Thank you all for your feedback
Seb

Make sure to do the following before submitting your issue - thanks!

- [x ] Make sure you're running the [latest release](https://github.com/mipstian/catch/releases/latest). You can find your version number at the bottom of the Help menu in Catch.
- [x ] [Check the FAQ](https://github.com/mipstian/catch/wiki/Frequently-Asked-Questions), your question might be answered there.
- [x ] [Check for an open issue](https://github.com/mipstian/catch/issues), and please comment on that issue instead of creating a duplicate.

**Comment by mipstian** [comment] 2016-10-01 17:00
News to me!

Could you:
1) See if Catch logs something interesting in Console.app when you update, and
2) Share your (non functional) feed URL, so I can try to reproduce?

**Comment by Seb137** [comment] 2016-10-01 19:06
Thank you for your quick answer!

1) here is the console feed
01/10/16 21:01:24,083 com.giorgiocalderolla.Catch.CatchFeedHelper[526]: Checking feed
01/10/16 21:01:24,083 com.giorgiocalderolla.Catch.CatchFeedHelper[526]: Downloading feed http://showrss.info/user/71233.rss?magnets=false&namespaces=true&name=clean&quality=hd&re=null
01/10/16 21:01:24,236 com.giorgiocalderolla.Catch.CatchFeedHelper[526]: Parsing feed
01/10/16 21:01:24,238 com.giorgiocalderolla.Catch.CatchFeedHelper[526]: Parsed 9 files
01/10/16 21:01:24,238 com.giorgiocalderolla.Catch.CatchFeedHelper[526]: Downloading files (if needed)
01/10/16 21:01:24,238 com.giorgiocalderolla.Catch.CatchFeedHelper[526]: Downloading file to folder for show The Blacklist
01/10/16 21:01:24,690 com.giorgiocalderolla.Catch.CatchFeedHelper[526]: Could not download http://reflektor.karmorra.info/torrent/DDD9E0A92B2006124D7F1C5BC8A6FB3D38014B10.torrent: Error Domain=com.giorgiocalderolla.Catch.CatchFeedHelper Code=-7 "Could not download file (bad status code 404)" UserInfo=0x7fec19904ff0 {NSLocalizedDescription=Could not download file (bad status code 404)}
01/10/16 21:01:24,690 com.giorgiocalderolla.Catch.CatchFeedHelper[526]: Downloading file to folder for show How to Get Away with Murder
01/10/16 21:01:25,674 com.giorgiocalderolla.Catch.CatchFeedHelper[526]: Could not download http://reflektor.karmorra.info/torrent/BAF2C8D6FDDF323826DE9B39FA045FD069A72E8C.torrent: Error Domain=com.giorgiocalderolla.Catch.CatchFeedHelper Code=-7 "Could not download file (bad status code 404)" UserInfo=0x7fec19d1b220 {NSLocalizedDescription=Could not download file (bad status code 404)}
01/10/16 21:01:25,675 Catch[480]: Feed Checker error (checking feed): Error Domain=com.giorgiocalderolla.Catch.CatchFeedHelper Code=-7 "Could not download file (bad status code 404)" UserInfo=0x7ffc7b009b70 {NSLocalizedDescription=Could not download file (bad status code 404)}

2) my feed link: http://showrss.info/user/71233.rss?magnets=false&namespaces=true&name=clean&quality=hd&re=null

Thank you again
Seb

**Comment by mipstian** [comment] 2016-10-01 19:09
Looks like the urls in your feed are valid but lead to nothing. Looks like a job for @adrinavarro :)

**Comment by mredrup** [comment] 2016-10-03 09:53
this does seem to be an issue with ShowRSS any idea as to how to contact them.  I cant actually see any tech support avenue.

**Comment by mipstian** [comment] 2016-10-03 11:27
Issue is on ShowRSS's end, but I'm gonna keep this open so we don't get a thousand duplicates.

The only known workaround is to use magnet links (change `magnets=false` to `magnets=true` in your feed URL). Otherwise, wait until the issue is resolved.

If configured like the guide says, Transmission opens no windows with magnet links (or ever): https://github.com/mipstian/catch/wiki/Configuration

**Comment by showrss** [comment] 2016-10-03 12:01
Traditional torrent files are becoming increasingly unreliable. showRSS cannot guarantee that a valid torrent will exist for a given info hash, so I recommend that everyone uses magnets instead.

**Comment by mredrup** [comment] 2016-10-03 18:50
Hi

Although this is probably a transmission problem I do have the window options unticked and a downloaded window still opens for each magnetic torrent.

Thank you
Mel

**Comment by mipstian** [comment] 2016-10-03 21:13
@mredrup are they both un-ticked? Do you have a valid default download directory?

**Comment by Shekral** [comment] 2016-10-03 21:25
@mredrup I had the same issue with Transmission and didn't care until Catch stopped being reliable when using torrent file. After searching on transmission forum, I finally found that you must have a default directory set (and not 'same as the torrent file') to avoid the window when adding a magnet.
See this thread : https://forum.transmissionbt.com/viewtopic.php?f=4&t=17705&p=72629&hilit=magnet#p72629

**Comment by mredrup** [comment] 2016-10-03 21:46
Thank you. I also found this solution after my last post and it does indeed solve the window issue.

**Comment by mipstian** [comment] 2016-10-03 21:57
Thanks! I've updated the Configuration wiki page with this info.

**Comment by mipstian** [comment] 2016-10-03 22:14
Added this 404 thing to the FAQ, closing this issue.

**Comment by crashtestoz** [comment] 2016-10-06 08:21
Try changing the **null** at the end of your rss feed link to **no**. This seemed to work for me.

From this:
http://showrss.info/user/71233.rss?magnets=false&namespaces=true&name=clean&quality=hd&re=null

To this:
http://showrss.info/user/71233.rss?magnets=false&namespaces=true&name=clean&quality=hd&re=no

**Closed** 2016-10-06 08:27 UTC
Labels: invalid
