### ISSUE TITLE
Link to new ShowRSS home

### ISSUE THREAD

**Issue by rogerfc** [mipstian/catch#88] opened 2015-12-15 15:39 UTC
The "Go to ShowRSS" link on the menu bar points to the "classic" ShowRSS home page. 
It would be great to have an option in the preferences to point to the new one instead: http://new.showrss.info

**Comment by dinkyrdj** [comment] 2015-12-15 15:41
I'd like to second this request. That option would be handy-dandy.

**Comment by mipstian** [comment] 2015-12-15 17:14
Dupe of #84 (see that for rationale)

**Closed by mipstian** 2015-12-15 17:14 UTC
