### ISSUE TITLE
Launch RSS goes to old showRSS site, not new one. 

### ISSUE THREAD

**Issue by bansonln** [mipstian/catch#85] opened 2015-11-26 16:24 UTC
I just updated my account to new showRSS but when I click on Launch showRSS in Catch it goes to the old site which my account is now disabled. Can this be fixed to point to the new showRSS site?

http://new.showrss.info

**Comment by mipstian** [comment] 2015-11-26 23:27
Duplicate of #84

**Closed by mipstian** 2015-11-26 23:27 UTC
